# Generated by Django 2.1.7 on 2019-02-28 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ascord', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(blank=True, default=0.0, max_length=20, null=True),
        ),
    ]
