# Generated by Django 2.1.7 on 2019-02-28 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ascord', '0003_product_in_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='in_stock',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
    ]
